import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Splash Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.wrapper} ${inter.className}`}>
        <div className={`${styles.container}`}>
          <h1 className={`${styles.header}`}>Lorem ipsum dolor sit amet, consectitour adipiscing elit.</h1>
          <p className={`${styles.description}`}>Lorem ipsum dolor sit amet, consectitour adipiscing elit.</p>
          <Link href="/game">
            <button className={`${styles.cta}`}>Let&apos;s play!</button>
          </Link>
        </div>
      </main>
    </>
  )
}
